// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/delete.ts";
import * as $2 from "./routes/api/get.ts";
import * as $3 from "./routes/api/isdone.ts";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/api/post.ts";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/Box.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Item.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/delete.ts": $1,
    "./routes/api/get.ts": $2,
    "./routes/api/isdone.ts": $3,
    "./routes/api/joke.ts": $4,
    "./routes/api/post.ts": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/Box.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Item.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
